#!/bin/zsh
for emacsclient in \
    /opt/homebrew/bin/emacsclient \
    /usr/local/bin/emacsclient \
    "$HOME/.local/bin/emacsclient"; do
  if [[ -x "$emacsclient" ]]; then
    "$emacsclient" -c -n --alternate-editor "" "$@"
    sleep 0.3
    osascript -e 'tell application "Emacs" to activate'
    exit 0
  fi
done
echo "emacsclient not found" >&2
exit 1
