{{- if ne (env "CHEZMOI_SKIP_EMACS_CONFIG") "1" }}
[".config/emacs"]
type = "git-repo"
url = "git@github.com:pasunboneleve/emacs.d.git"
refreshPeriod = "168h"
{{- end }}

[".config/dotfiles"]
type = "git-repo"
url = "git@github.com:pasunboneleve/dotfiles.git"
refreshPeriod = "168h"
